In [2]:
import torch

In [3]:
torch.__version__

'2.1.0'

### Torch Intro

In [4]:
# Create a tensor of 2 x 3 x 4
T = torch.Tensor(2, 3, 4)
T

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [5]:
T.random_()

tensor([[[ 9082223., 16125877.,  1762994.,  4226896.],
         [ 8348265.,  1788941.,  1196359., 12385809.],
         [14583986.,  6508581.,   861214.,  8502265.]],

        [[ 4997933.,  4747277., 15439391.,  4712681.],
         [ 1171321.,  3632997.,  6235200.,  3640622.],
         [ 6128877.,  5579782.,  4569728., 10484797.]]])

In [6]:
T.fill_(10)

tensor([[[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]],

        [[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]])

### Vectors (1D Tensors)

In [7]:
v = torch.tensor([1, 3, 2, 5], dtype=torch.float32)
v

tensor([1., 3., 2., 5.])

In [8]:
w = torch.arange(1, 5, dtype=torch.float32)
w

tensor([1., 2., 3., 4.])

In [18]:
z = v + w
z

tensor([2., 5., 5., 9.])

In [21]:
# Element-wise mult
z = v * w
z

tensor([ 1.,  6.,  6., 20.])

In [20]:
# Dot product
z = v @ w
z

tensor(33.)

### Matrices (2D Tensors)

In [22]:
A = torch.randn(2, 4)
A

tensor([[ 1.0351,  0.4883,  0.4483, -0.5128],
        [-0.4561,  0.4052, -0.2687,  0.5091]])

In [23]:
B = torch.randn(4, 3)
B

tensor([[-0.5708,  0.4685, -0.2693],
        [ 1.6512, -0.0389,  0.4275],
        [ 1.0852, -0.4612, -0.7548],
        [-0.1426, -0.3134,  1.7749]])

In [24]:
Z = A @ B
Z

tensor([[ 0.7751,  0.4199, -1.3185],
        [ 0.5652, -0.2651,  1.4025]])

In [25]:
Z.size()

torch.Size([2, 3])

In [26]:
Z.numel()

6

### Constructors

In [28]:
O = torch.zeros(5, 5)
O

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [29]:
I = torch.eye(9)
I

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Casting

In [9]:
torch.*Tensor?

torch.BFloat16Tensor
torch.BoolTensor
torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [10]:
a = v.double()
a.dtype

torch.float64

### Concatenation

In [11]:
v

tensor([1., 3., 2., 5.])

In [12]:
w

tensor([1., 2., 3., 4.])

In [13]:
torch.cat((v, w), 0)

tensor([1., 3., 2., 5., 1., 2., 3., 4.])

In [14]:
torch.cat((A, B))

NameError: name 'A' is not defined