## Matriks

Matriks merupakan array 2 dimensi yang memiliki baris dan kolom. 
Untuk matriks beranggotakan bilangan riil, kita dapat menuliskannya dengan notasi $\mathbf{A} \in \mathbb{R}^{m \times k}$:

$$
\mathbf{A} = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1k} \\
a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mk}
\end{bmatrix}
$$

Sebagai contoh, berikut sebuah matriks $\mathbf{A}$ berdimensi 3 x 4:

$$
\mathbf{A} = 
\begin{bmatrix}
0 & 1 & -2.3 & 0.1 \\
1.3 & 4 & -0.1 & 1 \\
4.1 & -1 & 0 & 1.7
\end{bmatrix}
$$

### Pembentukkan matriks

Seperti halnya pada vektor, NumPy menyediakan berbagai cara untuk membentuk matriks.

**Hard-coded**

In [1]:
import torch
A = torch.tensor([
    [0, 1, -2.3, 0.1], 
    [1.3, 4, -0.1, 1], 
    [4.1, -1, 0, 1.7]
])

m, k = A.shape # get matrix dimension

print(f"Value: {A}")
print(f"Shape: {m, k}")

Value: tensor([[ 0.0000,  1.0000, -2.3000,  0.1000],
        [ 1.3000,  4.0000, -0.1000,  1.0000],
        [ 4.1000, -1.0000,  0.0000,  1.7000]])
Shape: (3, 4)


**Random**

In [2]:
A = torch.randn(5, 4)
print(f"A : \n{A}")

A : 
tensor([[ 0.2522, -0.7411, -0.0436,  0.5761],
        [-0.0903, -0.7518, -0.5611,  0.9922],
        [-2.1897,  0.6052,  0.6832, -1.9686],
        [ 2.3814,  1.1294,  0.5553, -1.2869],
        [-0.2259, -0.2119,  0.8788, -0.1476]])


**Matriks Nol, Identitas, Diagonal**

In [3]:
Z = torch.zeros((3, 3))
I = torch.ones((3, 3))
D = torch.diag(torch.ones(3))

print(f"Zeros: \n{Z}")
print(f"Ones: \n{I}")
print(f"Diagonal: \n{D}")

Zeros: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Diagonal: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Submatrix / Slicing**

In [5]:
A = torch.randint(-5, high=5, size=(4, 4))
print(f"A: \n{A}")

B = A[2:4, 2:4] # slicing
print(f"B: \n{B}")

A: 
tensor([[ 1, -1,  3, -2],
        [-2, -3, -5,  2],
        [-3,  3, -2, -1],
        [-3, -3,  3,  2]])
B: 
tensor([[-2, -1],
        [ 3,  2]])


**Penggabungan matriks**

Matriks dapat dibentuk dari penggabungan matriks-matriks lain dengan menggunakan `hstack()` (*horizontal merge*) atau `vstack()` (*vertical merge*)

In [6]:
A = torch.randn(3, 2)
B = torch.randn(3, 4)

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

C = torch.hstack((A, B)) # horizontal merge
print(f"(hstack) C shape: {C.shape}")

A = torch.randn(5, 3)
B = torch.randn(2, 3)

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

C = torch.vstack((A, B)) # vertical merge
print(f"(vstack) C shape: {C.shape}")

A shape: torch.Size([3, 2])
B shape: torch.Size([3, 4])
(hstack) C shape: torch.Size([3, 6])
A shape: torch.Size([5, 3])
B shape: torch.Size([2, 3])
(vstack) C shape: torch.Size([7, 3])


**Mengubah vektor dimensi $d$ menjadi matriks**

Pada NumPy, fungsi `reshape()` dapat mengubah bentuk atau dimensi dari vektor atau matriks tanpa mengubah data.

In [7]:
v = torch.randn(4)
print(f"v shape: {v.shape}")

M = torch.reshape(v, (1, 4))
print(f"M shape: {M.shape}")

w = M.flatten() # vectorization: go back to original vector
print(f"w shape: {w.shape}")

print(v == w)

v shape: torch.Size([4])
M shape: torch.Size([1, 4])
w shape: torch.Size([4])
tensor([True, True, True, True])


### Operasi Dasar Matriks

Diketahui matriks $\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times k}$, dan skalar $c \in \mathbb{R}$.

- **Penjumlahan**: $\mathbf{C} = \mathbf{A} + \mathbf{B}$
- **Pengurangan**: $\mathbf{C} = \mathbf{A} - \mathbf{B}$
- **Perkalian dengan skalar**: $\mathbf{C} = c \mathbf{A}$
- **Perkalian antar elemen matriks**: $\mathbf{C} = \mathbf{A} * \mathbf{B}$

In [8]:
A = torch.tensor([[0, 4], [7,0], [3,1]])
B = torch.tensor([[1, 2], [2,3], [0,4]])
C = A + B
print(f"Addition: \n{C}")

C = 2.5 * A
print(f"Scalar mult: \n{C}")

C = A * B
print(f"Element-wise mult: \n{C}")

Addition: 
tensor([[1, 6],
        [9, 3],
        [3, 5]])
Scalar mult: 
tensor([[ 0.0000, 10.0000],
        [17.5000,  0.0000],
        [ 7.5000,  2.5000]])
Element-wise mult: 
tensor([[ 0,  8],
        [14,  0],
        [ 0,  4]])


### Inner Product

#### Perkalian matriks-vektor

Perkalian matriks-vektor merupakan generalisasi inner product dari 2 vektor. Misal terdapat matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ dan vektor $\mathbf{v} \in \mathbb{R}^k$, perkalian matriks-vektor menghasilkan sebuah vektor baru $\mathbf{y} \in \mathbb{R}^m$:

$$
\mathbf{y} = \mathbf{A} \mathbf{v}
$$

In [9]:
A = torch.randn(5, 3)
v = torch.randn(3)

print(f"A: \n{A}")
print(f"v: \n{v}")

y = A @ v
print(f"Matrix-vector mult: \n{y}")

A: 
tensor([[-1.3240,  0.9305, -0.6140],
        [-0.0893,  0.6910,  0.5257],
        [-0.0222,  0.7500,  0.5476],
        [ 0.3137,  0.0094, -0.3567],
        [-1.3050, -0.0865, -0.9215]])
v: 
tensor([1.5348, 0.3060, 0.5473])
Matrix-vector mult: 
tensor([-2.0834,  0.3621,  0.4952,  0.2891, -2.5336])


#### Perkalian matriks-matriks
Diketahui matriks $\mathbf{A} \in \mathbb{R}^{m \times d}$ dan $\mathbf{B} \in \mathbb{R}^{d \times k}$, perkalian antar kedua matriks tsb menghasilkan matriks baru $\mathbf{C} \in \mathbb{R}^{m \times k}$:

$$
\mathbf{C} = \mathbf{A} \mathbf{B}
$$

In [10]:
A = torch.randint(-10, high=10, size=(4, 2))
B = torch.randint(-5, high=5, size=(2, 3))

print(f"A: \n{A}")
print(f"B: \n{B}")

C = A @ B
print(f"C: \n{C}")

A: 
tensor([[-10,   3],
        [  6,  -9],
        [ -7,   1],
        [ -4,  -1]])
B: 
tensor([[-5,  1,  1],
        [ 4, -1,  3]])
C: 
tensor([[ 62, -13,  -1],
        [-66,  15, -21],
        [ 39,  -8,  -4],
        [ 16,  -3,  -7]])


#### Transpos
Transpos merupakan operator untuk menukar posisi baris dan kolom matriks. Tranpos dari matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ ditulis dengan $\mathbf{A}^\top \in \mathbb{R}^{k \times m} $.

Sebagai contoh, diketahui matriks $\mathbf{A} \in \mathbb{R}^{2 \times 3}$
$$
\mathbf{A} = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Transpos dari matriks tsb adalah

$$
\mathbf{A}^\top = 
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

In [11]:
A = torch.randn(4, 2)
B = torch.randn(3, 2)

# C = A @ B # can't be computed! matrix B needs to be trasponsed

C = A @ B.T # B is transposed


print(f"B shape: {B.shape}")
print(f"B.T shape: {B.T.shape}")


B shape: torch.Size([3, 2])
B.T shape: torch.Size([2, 3])


### Inverse

**Left-inverse**: Matriks $\mathbf{X} \in \mathbb{R}^{k \times m}$ merupakan *left-inverse* dari matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ jika memenuhi:

$$
\mathbf{X} \mathbf{A} = \mathbf{I}
$$

**Right-inverse**: Matriks $\mathbf{X}$ merupakan *right-inverse* dari matriks $\mathbf{A}$ jika memenuhi:

$$
\mathbf{A} \mathbf{X} = \mathbf{I}
$$

Jika $\mathbf{X}$ memenuhi baik *left-inverse* maupun *right-inverse* di atas, maka $\mathbf{X}$ disebut sebagai matriks inverse dari $\mathbf{A}$ atau ditulis dengan $\mathbf{A}^{-1}$.

Syarat awal agar $\mathbf{A}$ memiliki inverse adalah harus berbentuk matriks segiempat, i.e., $\mathbb{R}^{m \times m}$.

In [17]:
X = torch.randint(-2, 10, size=(4, 4))
X = torch.tensor(X, dtype=torch.float32)

print(f"X: \n {X}")

Xinv = torch.inverse(X)
print(f"Inverse of X: \n {Xinv}")

print(f"{X @ Xinv}")
print(f"{Xinv @ X}")



X: 
 tensor([[-1.,  7.,  0., -1.],
        [ 0., -1.,  8.,  7.],
        [ 9., -2., -1., -1.],
        [ 9.,  6., -2.,  8.]])
Inverse of X: 
 tensor([[ 0.0297,  0.0149,  0.1100,  0.0045],
        [ 0.1321,  0.0035,  0.0011,  0.0136],
        [ 0.1087,  0.1168,  0.0895, -0.0775],
        [-0.1053,  0.0098, -0.1022,  0.0905]])
tensor([[ 1.0000e+00,  9.3132e-10,  0.0000e+00,  7.4506e-09],
        [ 1.4901e-08,  1.0000e+00,  1.6065e-08, -8.3819e-09],
        [-1.4901e-08,  0.0000e+00,  1.0000e+00, -5.5879e-09],
        [-1.1921e-07,  0.0000e+00, -5.9605e-08,  1.0000e+00]])
tensor([[ 1.0000e+00, -2.7940e-09,  9.3132e-10, -3.7253e-09],
        [ 8.3819e-09,  1.0000e+00,  0.0000e+00,  1.4901e-08],
        [-7.4506e-09,  4.4703e-08,  1.0000e+00, -5.9605e-08],
        [-7.4506e-09, -4.4703e-08,  0.0000e+00,  1.0000e+00]])


/var/folders/b9/jjp98g8j2mbcn65j0fgl0dzw0000gp/T/ipykernel_45825/3068695327.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


### Norm matriks

Konsep norm juga dapat diaplikasikan pada matriks yang merepresentasikan besaran skalar (*magnitude*) dari suatu matriks. 
Sebagai contoh, Euclidean norm dari matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ adalah:

$$
\| \mathbf{A} \| = \sqrt{\left( \sum_{i=1}^{m} \sum_{j=1}^{k} a^2_{ij} \right)}
$$

In [20]:
A = torch.rand((4, 3))
print(f"A: \n{A}")

print(f"Norm(A): {torch.norm(A)}")

A: 
tensor([[0.8939, 0.5246, 0.1485],
        [0.9371, 0.7116, 0.4570],
        [0.3421, 0.5689, 0.4858],
        [0.6688, 0.4131, 0.8019]])
Norm(A): 2.151106119155884
