## Matriks

Matriks merupakan array 2 dimensi yang memiliki baris dan kolom. 
Untuk matriks beranggotakan bilangan riil, kita dapat menuliskannya dengan notasi $\mathbf{A} \in \mathbb{R}^{m \times k}$:

$$
\mathbf{A} = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1k} \\
a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mk}
\end{bmatrix}
$$

Sebagai contoh, berikut sebuah matriks $\mathbf{A}$ berdimensi 3 x 4:

$$
\mathbf{A} = 
\begin{bmatrix}
0 & 1 & -2.3 & 0.1 \\
1.3 & 4 & -0.1 & 1 \\
4.1 & -1 & 0 & 1.7
\end{bmatrix}
$$

### Pembentukkan matriks

Seperti halnya pada vektor, NumPy menyediakan berbagai cara untuk membentuk matriks.

**Hard-coded**

In [1]:
import torch
A = torch.tensor([
    [0, 1, -2.3, 0.1], 
    [1.3, 4, -0.1, 1], 
    [4.1, -1, 0, 1.7]
])

m, k = A.shape # get matrix dimension

print(f"Value: {A}")
print(f"Shape: {m, k}")

Value: tensor([[ 0.0000,  1.0000, -2.3000,  0.1000],
        [ 1.3000,  4.0000, -0.1000,  1.0000],
        [ 4.1000, -1.0000,  0.0000,  1.7000]])
Shape: (3, 4)


**Random**

In [2]:
A = torch.randn(5, 4)
print(f"A : \n{A}")

A : 
tensor([[-0.5667, -0.9549, -0.1511, -0.0268],
        [-1.1908,  1.1531, -1.0063,  0.5480],
        [ 2.3592,  0.5208,  1.2168,  0.1762],
        [-0.2991, -0.5100, -0.6074, -0.9104],
        [-0.4850, -0.5041, -1.3742,  1.2502]])


**Matriks Nol, Identitas, Diagonal**

In [3]:
Z = torch.zeros((3, 3))
I = torch.ones((3, 3))
D = torch.diag(torch.ones(3))

print(f"Zeros: \n{Z}")
print(f"Ones: \n{I}")
print(f"Diagonal: \n{D}")

Zeros: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Diagonal: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Submatrix / Slicing**

In [4]:
A = torch.randint(-5, high=5, size=(4, 4))
print(f"A: \n{A}")

B = A[2:4, 2:4] # slicing
print(f"B: \n{B}")

A: 
tensor([[ 2, -1, -2, -3],
        [ 2, -3,  3, -4],
        [-5, -3, -1, -1],
        [-3, -5, -4, -5]])
B: 
tensor([[-1, -1],
        [-4, -5]])


**Penggabungan matriks**

Matriks dapat dibentuk dari penggabungan matriks-matriks lain dengan menggunakan `hstack()` (*horizontal merge*) atau `vstack()` (*vertical merge*)

In [5]:
A = torch.randn(3, 2)
B = torch.randn(3, 4)

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

C = torch.hstack((A, B)) # horizontal merge
print(f"(hstack) C shape: {C.shape}")

A = torch.randn(5, 3)
B = torch.randn(2, 3)

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

C = torch.vstack((A, B)) # vertical merge
print(f"(vstack) C shape: {C.shape}")

A shape: torch.Size([3, 2])
B shape: torch.Size([3, 4])
(hstack) C shape: torch.Size([3, 6])
A shape: torch.Size([5, 3])
B shape: torch.Size([2, 3])
(vstack) C shape: torch.Size([7, 3])


**Mengubah vektor dimensi $d$ menjadi matriks**

Pada NumPy, fungsi `reshape()` dapat mengubah bentuk atau dimensi dari vektor atau matriks tanpa mengubah data.

In [6]:
v = torch.randn(4)
print(f"v shape: {v.shape}")

M = torch.reshape(v, (1, 4))
print(f"M shape: {M.shape}")

w = M.flatten() # vectorization: go back to original vector
print(f"w shape: {w.shape}")

print(v == w)

v shape: torch.Size([4])
M shape: torch.Size([1, 4])
w shape: torch.Size([4])
tensor([True, True, True, True])


### Operasi Dasar Matriks

Diketahui matriks $\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times k}$, dan skalar $c \in \mathbb{R}$.

- **Penjumlahan**: $\mathbf{C} = \mathbf{A} + \mathbf{B}$
- **Pengurangan**: $\mathbf{C} = \mathbf{A} - \mathbf{B}$
- **Perkalian dengan skalar**: $\mathbf{C} = c \mathbf{A}$
- **Perkalian antar elemen matriks**: $\mathbf{C} = \mathbf{A} * \mathbf{B}$

In [7]:
A = torch.tensor([[0, 4], [7,0], [3,1]])
B = torch.tensor([[1, 2], [2,3], [0,4]])
C = A + B
print(f"Addition: \n{C}")

C = 2.5 * A
print(f"Scalar mult: \n{C}")

C = A * B
print(f"Element-wise mult: \n{C}")

Addition: 
tensor([[1, 6],
        [9, 3],
        [3, 5]])
Scalar mult: 
tensor([[ 0.0000, 10.0000],
        [17.5000,  0.0000],
        [ 7.5000,  2.5000]])
Element-wise mult: 
tensor([[ 0,  8],
        [14,  0],
        [ 0,  4]])


### Inner Product

#### Perkalian matriks-vektor

Perkalian matriks-vektor merupakan generalisasi inner product dari 2 vektor. Misal terdapat matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ dan vektor $\mathbf{v} \in \mathbb{R}^k$, perkalian matriks-vektor menghasilkan sebuah vektor baru $\mathbf{y} \in \mathbb{R}^m$:

$$
\mathbf{y} = \mathbf{A} \mathbf{v}
$$

In [8]:
A = torch.randn(5, 3)
v = torch.randn(3)

print(f"A: \n{A}")
print(f"v: \n{v}")

y = A @ v
print(f"Matrix-vector mult: \n{y}")

A: 
tensor([[-0.2658,  2.7013, -2.1775],
        [ 0.2778, -0.6002, -0.0570],
        [ 0.6318,  0.4194, -0.1213],
        [-0.1906,  1.8913, -1.5526],
        [ 1.1335,  2.1166, -0.9840]])
v: 
tensor([-0.2752,  0.1757,  0.2761])
Matrix-vector mult: 
tensor([-0.0534, -0.1976, -0.1337, -0.0439, -0.2117])


#### Perkalian matriks-matriks
Diketahui matriks $\mathbf{A} \in \mathbb{R}^{m \times d}$ dan $\mathbf{B} \in \mathbb{R}^{d \times k}$, perkalian antar kedua matriks tsb menghasilkan matriks baru $\mathbf{C} \in \mathbb{R}^{m \times k}$:

$$
\mathbf{C} = \mathbf{A} \mathbf{B}
$$

In [9]:
A = torch.randint(-10, high=10, size=(4, 2))
B = torch.randint(-5, high=5, size=(2, 3))

print(f"A: \n{A}")
print(f"B: \n{B}")

C = A @ B
print(f"C: \n{C}")

A: 
tensor([[-7,  4],
        [ 7, -6],
        [-5, -6],
        [ 8,  9]])
B: 
tensor([[ 4, -5,  2],
        [ 0,  0, -4]])
C: 
tensor([[-28,  35, -30],
        [ 28, -35,  38],
        [-20,  25,  14],
        [ 32, -40, -20]])


#### Transpos
Transpos merupakan operator untuk menukar posisi baris dan kolom matriks. Tranpos dari matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ ditulis dengan $\mathbf{A}^\top \in \mathbb{R}^{k \times m} $.

Sebagai contoh, diketahui matriks $\mathbf{A} \in \mathbb{R}^{2 \times 3}$
$$
\mathbf{A} = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Transpos dari matriks tsb adalah

$$
\mathbf{A}^\top = 
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

In [10]:
A = torch.randn(4, 2)
B = torch.randn(3, 2)

# C = A @ B # can't be computed! matrix B needs to be trasponsed

C = A @ B.T # B is transposed


print(f"B shape: {B.shape}")
print(f"B.T shape: {B.T.shape}")


B shape: torch.Size([3, 2])
B.T shape: torch.Size([2, 3])


### Inverse

**Left-inverse**: Matriks $\mathbf{X} \in \mathbb{R}^{k \times m}$ merupakan *left-inverse* dari matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ jika memenuhi:

$$
\mathbf{X} \mathbf{A} = \mathbf{I}
$$

**Right-inverse**: Matriks $\mathbf{X}$ merupakan *right-inverse* dari matriks $\mathbf{A}$ jika memenuhi:

$$
\mathbf{A} \mathbf{X} = \mathbf{I}
$$

Jika $\mathbf{X}$ memenuhi baik *left-inverse* maupun *right-inverse* di atas, maka $\mathbf{X}$ disebut sebagai matriks inverse dari $\mathbf{A}$ atau ditulis dengan $\mathbf{A}^{-1}$.

Syarat awal agar $\mathbf{A}$ memiliki inverse adalah harus berbentuk matriks segiempat, i.e., $\mathbb{R}^{m \times m}$.

In [11]:
X = torch.randint(-2, 10, size=(4, 4))
X = torch.tensor(X, dtype=torch.float32)

print(f"X: \n {X}")

Xinv = torch.inverse(X)
print(f"Inverse of X: \n {Xinv}")

print(f"{X @ Xinv}")
print(f"{Xinv @ X}")



X: 
 tensor([[ 8.,  5.,  8.,  5.],
        [ 6.,  6., -2.,  9.],
        [ 1.,  2.,  2., -2.],
        [ 2.,  1.,  1.,  3.]])
Inverse of X: 
 tensor([[ 1.3061,  0.4898, -2.1837, -5.1020],
        [-0.7143, -0.1429,  1.4286,  2.5714],
        [-0.4286, -0.2857,  0.8571,  2.1429],
        [-0.4898, -0.1837,  0.6939,  2.1633]])
tensor([[ 1.0000e+00,  0.0000e+00,  9.5367e-07, -3.8147e-06],
        [ 2.3842e-07,  1.0000e+00, -4.7684e-07, -1.9073e-06],
        [ 5.9605e-08,  2.9802e-08,  1.0000e+00, -4.7684e-07],
        [ 1.1921e-07,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
tensor([[ 1.0000e+00,  4.7684e-07,  4.7684e-07, -9.5367e-07],
        [ 0.0000e+00,  1.0000e+00, -2.3842e-07, -2.3842e-07],
        [ 0.0000e+00, -2.3842e-07,  1.0000e+00, -2.3842e-07],
        [-4.7684e-07, -2.3842e-07,  0.0000e+00,  1.0000e+00]])


/var/folders/b9/jjp98g8j2mbcn65j0fgl0dzw0000gp/T/ipykernel_90736/3068695327.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


### Norm matriks

Konsep norm juga dapat diaplikasikan pada matriks yang merepresentasikan besaran skalar (*magnitude*) dari suatu matriks. 
Sebagai contoh, Euclidean norm dari matriks $\mathbf{A} \in \mathbb{R}^{m \times k}$ adalah:

$$
\| \mathbf{A} \| = \sqrt{\left( \sum_{i=1}^{m} \sum_{j=1}^{k} a^2_{ij} \right)}
$$

In [12]:
A = torch.rand((4, 3))
print(f"A: \n{A}")

print(f"Norm(A): {torch.norm(A)}")

A: 
tensor([[0.1563, 0.1097, 0.8389],
        [0.6022, 0.7991, 0.4085],
        [0.3876, 0.8535, 0.8313],
        [0.5284, 0.7485, 0.7790]])
Norm(A): 2.2191340923309326
